# Controller to control end effector joints
hand_ee_controller:
  type: position_controllers/JointTrajectoryController
  joints: [joint_claw_1, joint_claw_2]

# Controller to continuously publish joint states/positions
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100000

